data <- read.csv('pca.csv')
str(data)
library(caTools)
set.seed(88)
split <- sample.split(train$class, SplitRatio = 0.8)
dresstrain <- subset(train, split == TRUE)
dresstest <- subset(train, split == FALSE)
model <- glm (class ~odor+gillsize +sporeprintcolor+gillcolor+stalksurfaceabovering + stalksurfacebelowring+ringtype+population, data = dresstrain, family = binomial)
summary(model)
predicttrain <- predict(model, type = 'response')
summary(predicttrain)
tapply(predicttrain,dresstrain$class,mean)
table(dresstrain$class, predicttrain > 0.5)
library("ROCR")
ROCRpred=prediction(predicttrain,dresstrain$class)
ROCRpref=performance(ROCRpred,"tpr","fpr")
plot(ROCRpref,colorize="TRUE",print.cutoffs.at=seq(0,1,0.1),text.adj=c(0.2,1.7))
predicttest=predict(model,type="response",newdata=dresstest)

